---
title: Country-Level Institutional Assessment and Review (CLIAR)
subtitle: Institutional Benchmarking
output: 
  word_document
params:
  base_country: NA
  comparison_countries: NA
  data: NA
  family_data: NA
---

```{r, setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.width = 9
)
```

```{r}

 # Auxiliary functions -----------------------------------------------------------------

  source(file.path("auxiliary",
                   "vars-by-family.R"))

  source(file.path("auxiliary",
                   "plots.R"))

  variable_names <-
    read_rds(file.path("data",
                       "variable_names.rds"))

  definitions <-
    read_rds(file.path("data",
                       "indicator_definitions.rds"))
  
  source <- 
    "Source: Authors’ elaboration using CLIAR’s Interactive Online Dashboard."
  
  note <- 
    paste0(
      "Note: ",
      "The bar reflects the simple average of the score for all subindicators included in a given institutional cluster. For each cluster, the x-axis shows the closeness to frontier \n
      (length of the bar), which captures the gap between a country’s performance and the best performer among countries for which data are available (global frontier). The large circles show ",
      params$base_country,
      "'s performance. The traffic lights coloring indicates areas where the largest institutional gaps exist in ",
      params$base_country,
      " relative to comparator countries, as follows: red = weak institutional capital (bottom 25 percent); yellow = emerging institutional capital (25 percent–50 percent); green = strong institutional capital (top 50 percent). See World Bank (2021) for a detailed discussion on the methodology as well as a detail description and sources of indicators in each institutional cluster."
    )
```

**Base country:** `r params$base_country`


**Comparison countries:** `r paste(params$comparison_countries, collapse = ", ")`

# Country overview

```{r}
params$family_data %>%
  static_plot(
    params$base_country,
    "Country overview", 
    title = FALSE,
    note = paste(
      source,
      str_wrap(note, 174),
      sep = "\n"
    )
  )
```

# Institutional families

```{r,  results = "asis"}
for (category in c("Strong", "Emerging", "Weak")) {
  
  families <-
    params$family_data %>%
    filter(country_name == params$base_country,
           str_detect(status, category)) %>%
    select(var_name) %>%
    unlist
  
  if (length(families) > 0) {
    
    family_names <- 
      paste(families, collapse = ", ")

    cat("\n##",
        category,
        "institutional capital:",
        family_names, 
        " \n")
  
    for (family in families) {
    
      vars <-
        variable_names %>%
        filter(family_name == family) %>%
        select(var_name) %>%
        unlist
    
      cat(
        "\n###",
        family,
        " \n"
      )
      
      plot(
        params$data %>%
          filter(var_name %in% vars) %>%
          static_plot(
            params$base_country,
            family,
            title = FALSE,
            note = source
          )
      )
      
      cat("\n")
    }
    
  }
}

```

# Appendix - Indicator definitions

```{r,  results = "asis"}
for (family in names(definitions)) {
  cat("\n##",
      family,
      "\n")
  
  print(
    knitr::kable(
      definitions[[family]],
      format = "pipe"
    )
  )
  
  cat("\n")
  
}
```
