
# GET INDICATORS FROM API 360 ----
#gov_indicators <- get_metadata360(site="gov", metadata_type = "indicators")
#tc_indicators <- get_metadata360(site="tc", metadata_type = "indicators")

#indicators_360 <- bind_rows(gov_indicators,tc_indicators)

# IDs from selected indicators
selected_indicators_1 <- c(
  290,   # Corruption / Percent of firms identifying the courts system as a major constraint
  #464, #DOING BUSINESS INDICATOR  #  Dealing with construction permits: Procedures
  #472, #DOING BUSINESS INDICATOR  # Registering property: Cost
  #477,	#DOING BUSINESS INDICATOR  # Enforcing contracts: Cost
  #482	Resolving insolvency: Cost                    # ONLY ON DEFINITIONS
  519,   # Extent of market dominance
  633,   # Property rights (WEF)
  663,   # Diversion of public funds
  665,   # Public trust in politicians
  667,   # Irregular payments and bribes
  671,   # Favoritism in decisions of government officials
  683,   # Wastefulness of government spending
  685,   # Efficiency of legal framework in settling disputes
  687,   # Transparency of government policymaking
  691,   #	Efficiency of legal framework in challenging regs
  697,   #	Effectiveness of antimonopoly policy
  #719,  #	Prevalence of trade barriers
  723,	 # Burden of customs procedures
  #747,   # Index of economic freedom score          # ONLY ON DEFINITIONS
  3276,  # Corruption
  #3285,	 # Foreign Currency Regulations               # DIFFERENT VALUES
  3289,	 # Restrictive Labor Regulations
  3305,	 # Administrative burdens on startups
  3307,	 # Explicit barriers to trade and investment
  3308,	 # Other barriers to trade and investment
  3310,  #  Use of command and control regulation
  3311,	 # Price controls
  3323	 # Complexity of regulatory procedures
)

# API WASNT ABLE TO GET ALL TOGETHER
selected_indicators_2 <- c(
  3326,	 # Governance of state-owned enterprises
  3328,	 # Regulatory protection of incumbents
  #3451,  # Government Online Service Index
  #3469,  # E-Participation Index, 0-1 (best)
  #24840, #DOING BUSINESS INDICATOR # Paying taxes: Time
  27470, # Revised Combined Polity Score
  #27885, # Publicized laws and government data
  27889, # Right to information
  27894, # Complaint mechanisms
  27900, # Freedom of opinion and expression is effectively guaranteed
  27919, # People can access and afford civil justice
  #28833, #DOING BUSINESS INDICATOR  # Resolving insolvency Outcome
  #28782, #  Steering Capability
  #30823, # Central Bank independence                # NO RECENT DATA
  #31001, #  Efficiency of the banking supervisory authority
  #31003, #  Efficiency of the financial market supervisory authority
  #31088, #  Financial sector: competition regulation # ID NOT FOUND 24-09-2021
  #31115, #  Freedom of entry for foreigners # ID NOT FOUND 24-09-2021
  40294, #  Ease of starting a business
  40418, #  Ease of getting credit
  40432 #  Ease of protecting minority investors
  #40822  # 3. Undue influence
  #40985 #  Civil Liberties                    # STRANGE VALUES
  #40986, # Political Rights                   # STRANGE VALUES
)

selected_indicators_3 <- c(
  #41008, #	Burden of government regulation, 1-7 (best)
  41031, #  Regulatory governance score
  #41189, #  Procurement
  41305, #  Burden of customs procedures, 1-7 (best)
  41619, #  GCI 4.0: Global Competitiveness Index 4.0
  #41629, #  GCI 4.0: 1.E Undue influence and corruption
  41703, #  GCI 4.0: 7.A Domestic competition
  41714, #  GCI 4.0: Efficiency of the clearance process
  41794, #  Absence of corruption (Global States of Democracy)
  41827, #  Civil society participation
  41881, #  Engaged society
  #41883, #  Executive constraints          # POLITICAL ISSUE
  41857, #  CSO entry and exit
  41918, #  Freedom of academic and cultural expression
  #41932, #  Fundamental rights               # POLITICAL ISSUE
  41951, #  Judicial accountability
  #41953 #	Judicial independence       # ONLY ON DEFINITIONS
  #41955, #  Law  and order            # POLITICAL ISSUE
  41981, #  Lower chamber female legislators
  42024, #  Power distributed by gender
  42025, #  Power distributed by social group
  42026, #  Power distributed by socio-economic position
  #42084, #	Rigorous and impartial public administration
  #42602, #DOING BUSINESS INDICATOR #  Resolving insolvency: Strength of insolvency framework index
  43034, #  Hiring and firing practices, 1-7 (best)
  43050  #  GCI 4.0: Border clearance efficiency
)

governance_data <- c(
  42099, # SOE board of directors independence (Mining)
  42100, # SOE board of directors independence (Oil & Gas)
  #42105, # SOE corporate governance practice (Mining)
  #42106, # SOE corporate governance practice (Oil & Gas)
  42161, # SOE-government transfers governance rule (Mining)
  42162, # SOE-government transfers governance rule (Oil & Gas)
  42092, # SOE annual report disclosure (Oil & Gas)
  42091, # SOE annual report disclosure (Mining)
  42107, # SOE financial audit requirement (Mining)
  42108, # SOE financial audit requirement (Oil & Gas)
  42141, # SOE report legislative review requirement (Mining)
  42142  # SOE report legislative review requirement (Oil & Gas)
)

# Get data360
data_api_1 <- get_data360(
  indicator_id = selected_indicators_1,
  output_type = 'long')

data_api_2 <- get_data360(
  indicator_id = selected_indicators_2,
  output_type = 'long')

data_api_3 <- get_data360(
  indicator_id = selected_indicators_3,
  output_type = 'long')

data_api_governance <- get_data360(
  indicator_id = governance_data,
  output_type = 'long')

data_api_governance <- data_api_governance %>%
  mutate(
    Indicator = case_when(
      Indicator == "SOE board of directors independence (Mining)" ~ "SOE board of directors independence",
      Indicator == "SOE board of directors independence (Oil & Gas)" ~ "SOE board of directors independence",
      #Indicator == "SOE corporate governance practice (Mining)" ~ "SOE corporate governance practice",
      #Indicator == "SOE corporate governance practice (Oil & Gas)" ~ "SOE corporate governance practice",
      Indicator == "SOE-government transfers governance rule (Mining)" ~ "SOE-government transfers governance rule",
      Indicator == "SOE-government transfers governance rule (Oil & Gas)" ~ "SOE-government transfers governance rule",
      Indicator == "SOE annual report disclosure (Oil & Gas)" ~ "SOE annual report disclosure",
      Indicator == "SOE annual report disclosure (Mining)" ~ "SOE annual report disclosure",
      Indicator == "SOE financial audit requirement (Mining)" ~ "SOE financial audit requirement",
      Indicator == "SOE financial audit requirement (Oil & Gas)" ~ "SOE financial audit requirement",
      Indicator == "SOE report legislative review requirement (Mining)" ~ "SOE report legislative review requirement",
      Indicator == "SOE report legislative review requirement (Oil & Gas)" ~ "SOE report legislative review requirement"
    )
  ) %>%
  group_by(`Country ISO3`,`Country Name`,Indicator,Period) %>%
  summarise(Observation = mean(Observation, na.rm=T))

data_api <-
  bind_rows(
    data_api_1,
    data_api_2,
    data_api_3,
    data_api_governance
  )

data_api <-
  data_api %>%
  mutate(
    Indicator = str_trim(Indicator)
  )

# Cleaning API data ----
data_api <- data_api %>%
  rename(
    country_code = `Country ISO3`,
    country_name = `Country Name`,
    value = Observation
  ) %>%
  arrange(
    Indicator,country_name
  ) %>%
  separate(
    Period,into = c("Year1","year"),sep="-",remove = F
  ) %>%
  mutate(
    year = ifelse(is.na(year),as.character(Period),year)
  ) %>%
  select(
    -c(`Subindicator Type`,Period,Year1)
  ) %>%
  filter(
    !is.na(value)
  ) %>%
  complete(
    nesting(country_code, country_name),
    nesting(Indicator, year),
    fill = list(value = NA)
  ) %>%
  pivot_wider(
    id_cols = c(country_name,country_code,year),
    names_from = var
  ) %>%
  # SC: methodological note for PRM indicates that 1998 and 2013 indicators are comparable, but not with 2018 due to change in methodology
  # --> drop if year ==2018
  #mutate(
  #  across(
  #    c(barriers_startups:protection_incumbents),
  #    ~ifelse(year==2018, NA, .x)
  #  )
  #) %>%
  # Fix vars with opposite scale
  # reason: for the CTF methodology, we need for all indicators that "higher values" means "better performance"
  # freedom house: Countries are graded between 1 (most free) and 7 (least free).
#mutate(
#  across(
#    c(e_fh_pr,e_fh_cl),
#    ~(8 - .x)
#  )
#) %>%
# transform missing
mutate(
  e_p_polity = ifelse(e_p_polity < -10, NA, e_p_polity)
) %>%
  # PRM indicators: Countries are graded between 0 (less control/involvement) and 6 (more control/involvement)
  mutate(
    across(
      c(
        governance_soe,
        price_controls,
        command_control,
        complexity_procedures,
        barriers_startups,
        protection_incumbents,
        barriers_trade_expl,
        barriers_trade_oth
      ),
      ~(6 - .x)
    )
  ) %>%
  filter(
    year >= 1950   # variable e_p_polity has values since 1800, filter to reduce # of rows
  ) %>%
  select(
    country_code,year,
    all_of(var_api)
  )

var_matched_api <- data_api %>%
  select(-c(country_code, year)) %>%
  skim() %>%
  select(skim_variable) %>%
  .$skim_variable

missing_var_api <- setdiff(var_api,var_matched_api)
