# Import data from Stata

## Load packages

```{r}
packages <- c("tidyverse",
              "here",
              "data360r",
              "skimr",
              "haven")

pacman::p_load(packages,
               character.only = TRUE)
```

## Load raw data

```{r}
data_original <- read_rds(here("data",
                               "data_cleaned",
                               "merged_for_residuals.rds"))

additions <- 
  read_dta(here("data",
                "data_raw",
                "20211118_new_additions_notGov360.dta"))

source(file.path("app/auxiliary",
                 "vars-by-family.R"))
```

## Clean original data

```{r}
data_cleaned <- data_original %>%
  # Rename variables
  rename(
    country_name = countryname,
    country_code = code,
    telecom_infr = telecommunicationinfrastructurei,
    daigov_2016 = daigovernmentsubindex_2016,
    contract_manag_score = contract_management_score,
    perf_guarantee_score = performance_guarantee_score,
    proc_mean_score = mean_score,
    f6_regulatoryenf = f6_regulatoryenforcement,
    efw_integrity_legalsys = efw_integrityofthelegalsystem,
    efw_contracts_enf = efw_legalenforcementofcontracts,
    efw_businessreg = efw_businessregulations,
    efw_free_foreign_curr = efw_freedom_foreign_curr,
    protect_minority_ov = protect_minority_overall,
    efficiency_superv_bank = efficiancy_supervision_banking,
    efficiency_superv_fin = efficiancy_supervision_finmkt,
    getting_credit = bl,
    insolvency_framework = resolvinginsolvencystrength,
    credit_registry_cov = gettingcreditcreditregistry,
    #rigorous_impartial_pa = v2clrspct,
    barriers_trade_expl = barriers_trade_explicit,
    barriers_trade_oth = barriers_trade_other,
    cbi = lvau,
    efw_inv_restr = efw_foreign_invest_restr,
    efw_tourist = efw_freedomofforeignerstovisit
  ) %>%
  # Fix vars with opposite scale
  # reason: for the CTF methodology, we need for all indicators that "higher values" means "better performance"
  # freedom house: Countries are graded between 1 (most free) and 7 (least free).
  mutate(
    across(
      c(e_fh_pr,e_fh_cl),
      ~(8 - .x)
    )
  ) %>%
  # transform missing
  mutate(
    e_p_polity = ifelse(e_p_polity < -10, NA, e_p_polity)
  ) %>%
  # PRM indicators: Countries are graded between 0 (less control/involvement) and 6 (more control/involvement)
  mutate(
    across(
      c(governance_soe,price_controls,command_control,complexity_procedures,barriers_startups,protection_incumbents,barriers_trade_expl,barriers_trade_oth),
      ~(6 - .x)
    )
  ) %>%
  mutate(
    country_name = ifelse(country_name == "ksv", "Kosovo", country_name),
    country_name = ifelse(country_name == "tmp", "Timor-Leste", country_name)
  )

extra_groups <- data_cleaned %>%
  select(country_name,country_code, lac,lac6,structural) %>%
  unique

write_rds(extra_groups,
          here("data",
               "data_cleaned",
               "extra_groups.rds"))
```


## Additions with indicators that are not on Gov360

```{r}
additions <- 
  additions %>%
  filter(year >= 2015) %>%
  rename(country_code = iso3code) %>%
  select(-c(countryname,country,ccode)) %>%
  mutate(
    year=as.character(year)
  ) %>%
  labelled::remove_labels() %>%
  group_by(country_code) %>%
  summarise(
    across(
      where(is.numeric),
      mean,
      na.rm = TRUE
    )
  ) %>%
  mutate(
    across(
      where(is.numeric),
      ~ifelse(is.nan(.x),NA,.x)
    )
  ) %>%
  mutate(year = "2020") %>%
  relocate(year, .after = country_code)

data_binded <-
  data_selected %>%
  mutate(
    country_code=as.character(country_code),
    year=as.character(year)
  ) %>%
  left_join(
    additions,
    by = c("country_code","year")
  ) %>%
  mutate(
    #v2stfisccap = coalesce(v2stfisccap.x, v2stfisccap.y),
    v2clrspct = coalesce(v2clrspct.x, v2clrspct.y),
    v2stcritrecadm = coalesce(v2stcritrecadm.x, v2stcritrecadm.y)
  ) %>%
  mutate(
    proff1 = proff1*(-1)
  )
```
