# Set up 

## Packages 

```{r}
packages <-
  c("tidyverse",
    "rmapshaper",
    "sf",
    "here")

pacman::p_load(
  packages,
  character.only = TRUE
)
```

## Input data 

```{r}
ctf <-
  read_rds(
    here(
      "data",
      "final",
      "closeness_to_frontier.rds"
    )
  )

raw_indicators <-
  read_rds(
    here(
      "data",
      "final",
      "compiled_indicators.rds"
    )
  )
```

## Official WB maps 

```{r}
world_map <-
  read_sf(
    here(
      "data",
      "raw",
      "WB_countries_Admin0_lowres.geojson"
    )
  )

disputed_areas <-
  read_sf(
    here(
      "data",
      "raw",
      "disputed_areas",
      "WB_disputed_areas_Admin0_10m.shp"
    )
  )
```

# Clean maps 

```{r}
disputed_areas <-
  disputed_areas %>%
  select(WB_A3) %>%
  filter(!is.na(WB_A3))

world_map <-
  world_map %>%
  select(WB_A3) 

world_map <-
  world_map %>%
  bind_rows(
    disputed_areas
  ) %>%
  rename(
    country_code = WB_A3
  ) %>%
  ms_simplify(
    keep = 0.04,
    keep_shapes = T
  )

st_crs(world_map) <- "WGS84"

world_map <-
  world_map %>%
  st_transform("+proj=robin")

```


# Combine maps and data

## Closeness to frontier

```{r}
ctf_map <-
  world_map %>%
  left_join(
    ctf
  ) 
```

## Raw data

```{r}
raw <-
  raw_indicators %>%
  pivot_longer(
    cols = 4:ncol(.)
  ) %>%
  filter(!is.na(value)) %>%
  group_by(country_name, country_code, name) %>%
  filter(year == max(year)) %>%
  ungroup %>%
  pivot_wider(
    values_from = c(value, year),
    names_from = name
  )

raw_map <-
  world_map %>%
  left_join(
    raw
  ) 
```


# Save datasets

```{r}
raw_map %>%
  write_rds(
    here(
      "app",
      "data",
      "indicators_map.rds"
    )
  )

ctf_map %>%
  write_rds(
    here(
      "app",
      "data",
      "closeness_to_frontier_map.rds"
    )
  )
```
