# Process manual additions

## Load packages

```{r}
packages <- 
  c(
    "tidyverse",
    "here",
    "haven",
    "labelled"
  )

pacman::p_load(packages, character.only = TRUE)
```

## Import data
```{r}
additions <- 
  read_dta(
    here(
      "data",
      "data_raw",
      "20211118_new_additions_notGov360.dta"
    )
  )
```

## Clean data
```{r}
additions_clean <-
  additions %>%
  filter(year >= 2015) %>%
  rename(country_code = iso3code) %>%
  select(-c(countryname,country,ccode)) %>%
  mutate(
    year=as.character(year)
  ) %>%
  remove_labels() %>%
  group_by(country_code) %>%
  summarise(
    across(
      where(is.numeric),
      ~ . %>% 
        mean(na.rm = TRUE) %>%
        replace(is.nan(x), NA)
    )
  ) %>%
  mutate(
    across(
      where(is.numeric),
      ~ifelse(is.nan(.x),NA,.x)
    )
  ) %>%
  mutate(
    year = "2020",
    proff1 = proff1*(-1),
    country_code=as.character(country_code),
    year=as.character(year)
  ) %>%
  relocate(year, .after = country_code) %>%
  ## Keep only indicators from original data ----
  select(
    country_code,
    year,
    all_of(vars_additions)
  )
```

## Save data

```{r}
write_rds(
  additions_clean,
  here(
    "data",
    "clean",
    "additional_data.rds"
  )
)

```
