# Keep only vars of interest
data_selected <- data_cleaned %>%
  select(
    -c(country,iso3code)
  ) %>%
  # SC: methodological note for PRM indicates that 1998 and 2013 indicators are comparable, but not with 2018 due to change in methodology
  # --> drop if year ==2018
  mutate(
    across(
      c(barriers_startups:protection_incumbents),
      ~ifelse(year==2018, NA, .x)
    )
  )

# KEEP ONLY INDICATORS THAT SHOULD BE FROM ORIGINAL DATA AND ADDITIONS ----
data_original <-
  data_binded %>%
  select(
    c(
      country_code,country_name,year,
      gtmi,
      #v2stfisccap,
      v2clrspct,
      v2stcritrecadm,
      scopeofstateownedenterprises,
      governmentinvolvementinnetworkse,
      directcontroloverbusinessenterpr,
      price_controls,
      command_control,
      #proff1,
      #close2,
      efw_free_foreign_curr,
      efw_labor_mkt_reg,
      govreg_burden,
      lpi_clearance_eff,
      open_data_barometer,
      proc_mean_score,
      regulatory_governance,
      #rigorous_impartial_pa,
      v2juaccnt,
      v2lgfemleg,
      v2pepwrgen,
      v2pepwrses,
      v2pepwrsoc,
      f1_govpowers,  # POL ISSUE
      f3_security,   # POL ISSUE
      f4_rights,     # POL ISSUE
      # VAR ONLY IN ORIGINAL DATA, NOT FOUND IN API
      f5_opengov,
      nontariff_barriers,
      efw_tourist,
      efw_credit_mkt_reg,
      efw_capitalcontrols,
      efw_inv_restr,
      competition_rules_fin,
      efficiency_superv_bank,
      efficiency_superv_fin,
      cbi,
      insolvency_framework,
      collective_barg,
      empl_protection_perm,
      empl_protection_temp,
      union_density,
      minimum_wage_ratio,
      f8_criminaljustice,
      efw_integrity_legalsys,
      e_fh_pr,
      e_fh_cl,
      v2lgqugen,
      f6_regulatoryenf,
      centregov_mean,
      v2xcs_ccsi
    )
  )

var_original <- data_original %>%
  select(-c(country_code,country_name,year)) %>%
  skim() %>%
  select(skim_variable) %>%
  .$skim_variable


var_api <- setdiff(vars_all,var_original)



data_mixed <- data_original %>%
  left_join(
    data_api,
    by = c("country_code","year")
  )

# Explore dataset
#skim(data_selected)

write_rds(data_mixed,
          here("data",
               "data_cleaned",
               "selected_vars.rds"))

write_rds(data_mixed,
          here("app",
               "data",
               "raw_data.rds"))

rm(data_binded,data_selected,data_cleaned,data_api_2, data_api_3,data_api_1)
gc()
